name: Build

on:
  push:
  pull_request:
    branches: [master]

permissions:
  contents: write  # Required for creating releases

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install rgbds
        run: |
          mkdir /tmp/rgbds
          cd /tmp
          wget https://github.com/gbdev/rgbds/releases/download/v0.9.2/rgbds-0.9.2-linux-x86_64.tar.xz
          tar xf rgbds-0.9.2-linux-x86_64.tar.xz -C rgbds
          cd rgbds
          sudo ./install.sh
      - name: Build ROM
        run: make
      - name: Upload ROM artifact
        uses: actions/upload-artifact@v4
        with:
          name: mbc3Otest
          path: mbc3Otest.gb
      - name: Determine if tag is on master
        id: prerelease
        if: github.ref_type == 'tag'
        run: |
          git fetch origin master
          if git merge-base --is-ancestor HEAD origin/master; then
            echo "prerelease=false" >> "$GITHUB_OUTPUT"
          else
            echo "prerelease=true" >> "$GITHUB_OUTPUT"
          fi
      - name: Create release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: mbc3Otest.gb
          generate_release_notes: true
          prerelease: ${{ steps.prerelease.outputs.prerelease }}
