name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install rgbds
        run: |
          mkdir /tmp/rgbds
          cd /tmp
          wget https://github.com/gbdev/rgbds/releases/download/v0.9.2/rgbds-0.9.2-linux-x86_64.tar.xz
          tar xf rgbds-0.9.2-linux-x86_64.tar.xz -C rgbds
          cd rgbds
          sudo ./install.sh
      - name: Build ROM
        run: make
      - name: Upload ROM artifact
        uses: actions/upload-artifact@v4
        with:
          name: main-gb
          path: main.gb
